export const brochureSearchIndex = [
  { page: 1, text: "Reimagining desserts imported ingredients brochure" },
  { page: 2, text: "Callebaut Finest Belgian chocolate bakery pastry confectionery dark milk white couverture single origin Ecuador Sao Thome Madagascar Brazil Arriba Java" },
  { page: 3, text: "No added sugar chocolate maltitol Tintoretto praline fillings Gold Ruby orange flavoured chocolate" },
  { page: 4, text: "Truffle shells praline fillings hazelnut pistachio cocoa nibs Paillete Feuilletine Mycryo cocoa butter" },
  { page: 5, text: "Chocolate powder Mona Lisa Crispearls dark milk white salted caramel Ruby crunchy cereals" },
  { page: 6, text: "Cacao Barry premium chocolates France Tanzania Saint Domingue Venezuela Ghana Alto El Sol Ocoa Inaya couverture" },
  { page: 7, text: "Cacao Barry pure cocoa products Plein Arome Grand Caraque Extra Brute Cara Crakine praline Feuilletine" },
  { page: 8, text: "Van Houten premium dark milk couverture chocolate Barry Callebaut Singapore cocoa desserts" },
  { page: 9, text: "Pizza flour T55 strong flour" },
  { page: 10, text: "Dawn Foods fruit pie fillings cherry apple raspberry black currant strawberry blueberry passion fruit apricot" },
  { page: 11, text: "Natural fruit fillings bake stable blueberry apple sour cherry strawberry apricot raspberry passion fruit pineapple" },
  { page: 12, text: "Premium bakery ice cream ingredients Dubai chocolate Chocomilky peanut caramel blueberry coffee baklava pistachio walnut" },
  { page: 13, text: "Pistachio cookies healthy range fruit pastes strawberry pear hazelnut mint" },
  { page: 14, text: "Pernigotti flavours from around the world" },
  { page: 15, text: "Ravifruit frozen fruits purees IQF apricot banana blackberry blueberry coconut mango cherry passion fruit raspberry strawberry" },
  { page: 16, text: "Elle Vire Professionnel whipping cream extra dry butter cream cheese mascarpone dairy pastry croissant" },
  { page: 17, text: "Corman butter cream pastry croissant Sculpture whipping specialty Belgian dairy" },
  { page: 18, text: "Frozen fruits purees smoothies IQF strawberry mango apple banana blackberry blueberry coconut lime raspberry cherry" },
  { page: 19, text: "Switz baked treats snacks pastries samosas bakery frozen food" },
  { page: 20, text: "Ulmer Spatz bakery solutions European bread Kraftkorn Sima cake mix baguette rye flour bread improver Foccacia" },
  { page: 21, text: "Aryzta frozen food solutions convenience bakery bread rolls morning savoury bakery" },
  { page: 22, text: "Sosa fine ingredients Spain gastronomy culinary freeze dried fruit texturizers gelatine dextrose maltodextrin lecithin natural colour Panko" },
  { page: 23, text: "Les vergers Boiron frozen fruits purees France chefs bartenders brewers" },
  { page: 24, text: "PCB Creations cocoa butter colours powder colours chocolate decorations Italian velvet sprays" },
  { page: 25, text: "Carpigiani ice cream gelato equipment pasteurisers batch freezers Chocolate World tempering cooling tunnels enrobing moulding" },
  { page: 26, text: "Professional pizza ovens Irinox multifunction blast freezer freshness equipment" },
  { page: 27, text: "Friulinox blast freezers ISA display cabinets ice cream pastry chocolate Sammic mixers Pavoni pastry cutters sprayers" },
  { page: 28, text: "International Alliance machinery Delta Nutritives Mumbai Delhi Bangalore contact" },
];
