import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, ClipboardCheck, FileText, MapPin, PackageCheck, Search, Truck } from "lucide-react";
import { industries, products, getIndustry, slugify, bakeryProductGroups, chocolateProductGroups, dairyProductGroups, beverageProductGroups, iceCreamProductGroups, fruitProductGroups, hydrocolloidProductGroups, sweetenerProductGroups, functionalProductGroups, nutraceuticalProductGroups, additiveProductGroups } from "../data/catalog";
import { industryContent } from "../data/industry-content";
import { partnersForIndustry } from "../data/partners";
import { DetailHeader, DetailFooter, PageCta, styles } from "./DetailChrome";
import BakeryCategoryShowcase from "./BakeryCategoryShowcase";
import IndustrySelectionPath from "./IndustrySelectionPath";

const siteUrl = "https://www.vikranthchem.com";
export function generateStaticParams() { return industries.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }) {
  const industry = getIndustry((await params).slug); const content = industry && industryContent[industry.slug];
  if (!industry || !content) return {};
  const canonical = `/industries/${industry.slug}`;
  return { title: content.title, description: content.description, keywords: [`${industry.name} supplier Chennai`, `${industry.name} supplier India`, `B2B ${industry.name.toLowerCase()}`, `bulk ${industry.name.toLowerCase()}`], alternates: { canonical }, robots: { index: true, follow: true }, openGraph: { type: "website", url: canonical, title: content.title, description: content.description, siteName: "Vikranth Chemical Corporation", locale: "en_IN", images: [{ url: industry.image, alt: content.h1 }] }, twitter: { card: "summary_large_image", title: content.title, description: content.description, images: [industry.image] }, other: { "geo.region": "IN-TN", "geo.placename": "Chennai" } };
}
const groupMap = { "bakery-ingredients": [bakeryProductGroups, "Bakery"], "chocolate-confectionery": [chocolateProductGroups, "Chocolate & confectionery"], "dairy-ingredients": [dairyProductGroups, "Dairy"], "beverage-ingredients": [beverageProductGroups, "Beverage"], "ice-cream-ingredients": [iceCreamProductGroups, "Ice cream"], "fruit-processing": [fruitProductGroups, "Fruit processing"], "hydrocolloids-stabilizers": [hydrocolloidProductGroups, "Hydrocolloid & stabilizer"], "sweeteners-syrups-starches": [sweetenerProductGroups, "Sweetener, syrup & starch"], "functional-ingredients": [functionalProductGroups, "Functional ingredient"], "nutraceutical-pharma": [nutraceuticalProductGroups, "Nutraceutical & pharma"], "food-additives-preservatives": [additiveProductGroups, "Food additive & preservative"] };

export default async function IndustryPage({ params }) {
  const industry = getIndustry((await params).slug); const content = industry && industryContent[industry.slug]; if (!industry || !content) notFound();
  const items = industry.products.map((name) => products.find((product) => product.slug === slugify(name))).filter(Boolean);
  const partners = partnersForIndustry(industry.slug); const [groups, guideLabel] = groupMap[industry.slug] || [null, ""];
  const canonicalUrl = `${siteUrl}/industries/${industry.slug}`;
  const schema = [{ "@context": "https://schema.org", "@type": "CollectionPage", url: canonicalUrl, name: content.h1, description: content.summary, about: { "@id": `${siteUrl}/#organization` } }, { "@context": "https://schema.org", "@type": "ItemList", name: industry.name, itemListElement: items.map((item, i) => ({ "@type": "ListItem", position: i + 1, name: item.name, url: `${siteUrl}/products/${item.slug}` })) }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteUrl }, { "@type": "ListItem", position: 2, name: "Industries", item: `${siteUrl}/industries` }, { "@type": "ListItem", position: 3, name: industry.name, item: canonicalUrl }] }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: content.faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }];
  return <main className={`${styles.page} ${styles.industryPage}`}><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><DetailHeader />
    <section className={styles.industryHero}><img className={styles.industryHeroImage} src={industry.image} alt={`${industry.name} for commercial food production`} /><div className={styles.industryHeroShade} /><div className={styles.industryHeroInner}><div className={styles.crumbs}><Link href="/">Home</Link><span>/</span><Link href="/industries">Industries</Link><span>/</span><span>{industry.name}</span></div><div className={styles.industryHeroGrid}><div><span className={styles.heroKicker}>B2B ingredient sourcing · Chennai & India</span><h1>{content.h1}</h1><p>{content.summary}</p><div className={styles.heroActions}><Link href="#industry-products">Explore product range <ArrowRight size={16} /></Link><Link href="/contact#enquiry">Discuss your requirement</Link></div></div><aside className={styles.heroProof}><span>Procurement support</span><ul><li><PackageCheck /><b>Commercial quantities</b><small>Pack and MOQ confirmation</small></li><li><FileText /><b>Technical documents</b><small>COA, TDS and SDS requests</small></li><li><Truck /><b>Pan-India enquiries</b><small>Freight and serviceability checks</small></li></ul></aside></div></div></section>
    <div className={styles.industryContent}><IndustrySelectionPath industry={industry} content={content} />
      <section className={styles.applicationSection}><Heading number="02" eyebrow="Application & selection guide" title="Match the ingredient to what you make" text="Use these application groups to narrow the right ingredient family before confirming grade, process fit and availability." /><div className={styles.applicationGrid}>{content.applications.map(([name, description], i) => <article key={name}><span>0{i + 1}</span><h3>{name}</h3><p>{description}</p></article>)}</div></section>
      <section className={styles.productSection} id="industry-products"><Heading number="03" eyebrow={`${guideLabel} portfolio`} title="Explore available product families" text={`${items.length} listed products with grade, pack size, stock and manufacturer availability confirmed for each enquiry.`} />{groups ? <BakeryCategoryShowcase groups={groups} products={items} categoryLabel={industry.name} fallbackImage={industry.image} /> : null}</section>
      <section className={styles.procurementSection}><div className={styles.procurementVisual}><img src={industry.image} alt="" /><div><small>Built for professional buyers</small><strong>From requirement to a quote-ready brief.</strong></div></div><div className={styles.procurementCopy}><span className={styles.sectionNumber}>04</span><small className={styles.eyebrow}>A better enquiry gets a better answer</small><h2>Prepare your sourcing requirement</h2><p>{content.quote}</p><ol><li><ClipboardCheck /><span><b>Application & process</b><small>Finished product, batch and production conditions</small></span></li><li><Search /><span><b>Specification & documents</b><small>Grade, brand, COA, TDS, SDS or sample needs</small></span></li><li><MapPin /><span><b>Quantity & destination</b><small>Pack, monthly volume, timeline and delivery PIN code</small></span></li></ol><Link className={styles.primary} href="/contact#enquiry">Build your enquiry <ArrowRight size={16} /></Link></div></section>
      {partners.length > 0 && <section className={styles.partnerSection}><Heading number="05" eyebrow="Supplier network" title="Relevant suppliers and partners" text="Explore represented product portfolios and submit a requirement for current commercial availability." /><div className={styles.partnerGrid}>{partners.map((partner) => <Link className={styles.partnerTile} href={`/associates/${partner.slug}`} key={partner.slug}><div>{partner.logo ? <img src={partner.logo} alt={`${partner.name} logo`} /> : <b>{partner.name}</b>}</div><h3>{partner.name}</h3><span>Explore partner <ArrowRight size={14} /></span></Link>)}</div></section>}
      <section className={styles.faqSection}><div className={styles.faqIntro}><span className={styles.sectionNumber}>06</span><small className={styles.eyebrow}>Buyer questions, answered</small><h2>Frequently asked questions</h2><p>Direct answers to common sourcing and formulation questions for {industry.name.toLowerCase()}.</p></div><div className={styles.faqList}>{content.faq.map(([q, a], i) => <details key={q} open={i === 0}><summary><span>0{i + 1}</span>{q}<b>+</b></summary><p>{a}</p></details>)}</div></section>
    </div><PageCta title={`Need help selecting ${industry.name.toLowerCase()}?`} product={industry.name} /><DetailFooter /></main>;
}
function Heading({ number, eyebrow, title, text }) { return <div className={styles.sectionHeading}><div><span className={styles.sectionNumber}>{number}</span><small className={styles.eyebrow}>{eyebrow}</small><h2>{title}</h2></div>{text && <p>{text}</p>}</div>; }
