"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowRight, BadgeCheck, Boxes, FileCheck2, Headphones, MapPin, PackageCheck, ShieldCheck, Sparkles, Truck } from "lucide-react";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import styles from "./about.module.css";
import { partners } from "../data/partners";

const frameCount = 300;
const verifiedCustomerPermissions = false;
const frameUrl = index => `/about-sequence/frame-${String(index + 1).padStart(3, "0")}.webp`;
const frameIndexesForViewport = () => {
  const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  const count = reduced ? 1 : window.innerWidth <= 560 ? 72 : window.innerWidth <= 900 ? 150 : frameCount;
  if (count === 1) return [0];
  return Array.from({ length: count }, (_, index) => Math.round((index / (count - 1)) * (frameCount - 1)));
};
const chapters = [
  [0,74,"Chennai ingredient-sourcing partner","About Vikranth Chemical Corporation","Vikranth Chemical Corporation connects professional food businesses with bakery, chocolate, dairy, beverage and specialty ingredient options selected around defined production needs."],
  [75,148,"Application-led sourcing","The right ingredient starts with the right questions.","We begin with your application, required function, grade, quantity and documentation needs—then help identify suitable options for evaluation."],
  [149,223,"A dependable ingredient network","Established partners. Practical local support.","Our supplier relationships and Chennai enquiry route help professional buyers navigate availability, specifications, samples and repeat requirements."],
  [224,299,"Built for business continuity","Responsive service beyond the first order.","From initial product matching to documentation and repeat supply conversations, our focus is clear communication and dependable support."],
];

function drawCover(canvas,image){const ctx=canvas.getContext("2d");const ratio=Math.min(window.devicePixelRatio||1,2.5);const width=canvas.clientWidth,height=canvas.clientHeight;if(canvas.width!==width*ratio||canvas.height!==height*ratio){canvas.width=width*ratio;canvas.height=height*ratio}ctx.setTransform(ratio,0,0,ratio,0,0);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";ctx.fillStyle="#211007";ctx.fillRect(0,0,width,height);const scale=Math.max(width/image.naturalWidth,height/image.naturalHeight),rw=image.naturalWidth*scale,rh=image.naturalHeight*scale;ctx.drawImage(image,(width-rw)/2,(height-rh)/2,rw,rh)}

export default function AboutStory(){
  const sectionRef=useRef(null),canvasRef=useRef(null),imagesRef=useRef([]),currentFrame=useRef(0);
  const[loaded,setLoaded]=useState(0),[chapter,setChapter]=useState(0),[progress,setProgress]=useState(0);
  useEffect(()=>{gsap.registerPlugin(ScrollTrigger);let cancelled=false;const frameIndexes=frameIndexesForViewport();const activeFrameCount=frameIndexes.length;const images=Array.from({length:activeFrameCount},(_,index)=>{const image=new Image();image.decoding="async";image.src=frameUrl(frameIndexes[index]);image.onload=()=>{if(cancelled)return;setLoaded(value=>Math.min(frameCount,value+1));if(index===0&&canvasRef.current)drawCover(canvasRef.current,image)};return image});imagesRef.current=images;const playhead={frame:0};const render=()=>{const frame=Math.max(0,Math.min(activeFrameCount-1,Math.round(playhead.frame)));const sourceFrame=frameIndexes[frame];currentFrame.current=frame;setProgress(activeFrameCount === 1 ? 100 : (frame/(activeFrameCount-1))*100);const image=images[frame];if(image?.complete&&image.naturalWidth&&canvasRef.current)drawCover(canvasRef.current,image);const next=chapters.findIndex(item=>sourceFrame>=item[0]&&sourceFrame<=item[1]);if(next>=0)setChapter(previous=>previous===next?previous:next)};const tween=gsap.to(playhead,{frame:activeFrameCount-1,ease:"none",onUpdate:render,scrollTrigger:{trigger:sectionRef.current,start:"top top",end:"bottom bottom",scrub:.35,invalidateOnRefresh:true}});const resize=()=>{const image=images[currentFrame.current];if(image?.complete&&image.naturalWidth&&canvasRef.current)drawCover(canvasRef.current,image)};window.addEventListener("resize",resize,{passive:true});return()=>{cancelled=true;window.removeEventListener("resize",resize);tween.scrollTrigger?.kill();tween.kill()}},[]);
  useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const items=gsap.utils.toArray(".aboutReveal");const reveals=items.map((item,index)=>gsap.fromTo(item,{autoAlpha:0,y:34},{autoAlpha:1,y:0,duration:.8,ease:"power3.out",scrollTrigger:{trigger:item,start:"top 86%",once:true},delay:(index%3)*.06}));return()=>{reveals.forEach(tween=>{tween.scrollTrigger?.kill();tween.kill()})}},[]);
  const active=chapters[chapter];
  return <>
    <section ref={sectionRef} className={styles.sequence} aria-label="The Vikranth story"><div className={styles.sticky}><canvas ref={canvasRef} className={styles.canvas}/><div className={styles.shade}/><div className={styles.progress} style={{"--progress":`${progress}%`}}/><div className={styles.storyCopy}><span>{active[2]}</span><h1>{active[3]}</h1><p>{active[4]}</p></div>{loaded<12&&<div className={styles.loader}><Sparkles/><span>Preparing the Vikranth story</span><small>{Math.round((loaded/12)*100)}%</small></div>}<div className={styles.scrollCue}>Scroll to explore <span/></div></div></section>
    <section className={styles.aboutOverview} aria-labelledby="about-overview-title">
      <div className={styles.aboutOverviewLead + " aboutReveal"}><span className={styles.eyebrow}>About Vikranth Chemical Corporation</span><h2 id="about-overview-title">A Chennai ingredient-sourcing partner for food businesses.</h2><p>Vikranth supports professional buyers sourcing ingredients for bakery, chocolate, confectionery, dairy, beverages, ice cream, fruit processing, nutraceutical and other manufacturing applications. Exact grade, manufacturer, pack size, availability and commercial terms are confirmed per enquiry.</p><a className={styles.textLink} href="/products">Explore our ingredient range <ArrowRight/></a></div>
      <div className={styles.aboutOverviewImage + " aboutReveal"}><img src="/about-overview.webp" alt="Vikranth Chemical Corporation ingredient sourcing team" loading="lazy"/><div><span>Application-first support</span><b>Ingredients, people and practical supply conversations.</b></div></div>
    </section>
    {verifiedCustomerPermissions && <section className={styles.trustedCustomers} aria-labelledby="trusted-customers-title"><div className={styles.customerHeading + " aboutReveal"}><span id="trusted-customers-title" className={styles.eyebrow}>Trusted customers</span></div><div className={styles.customerMarquee} aria-label="Trusted customer logos"><div className={styles.customerMarqueeTrack}>{[['hershey.jpg','The Hershey Company'],['cavinkare.jpg','CavinKare'],['milka.jpg','Milka'],['lotte.jpg','Lotte'],['a2b.png','A2B Indian Veg Restaurant'],['nilgiris.png','Nilgiris'],['amrutanjan.png','Amrutanjan']].map(([logo,name],index)=><div className={styles.customerLogo} key={`${name}-${index}`}><img src={`/trusted-customers/${logo}`} alt={`${name} logo`}/></div>)}</div></div></section>}
    <section className={styles.whoWeAre} aria-labelledby="who-we-are-title"><div className={styles.whoMedia + " aboutReveal"}><img src="/about-who-we-are.webp" alt="Food ingredient samples reviewed for commercial sourcing" loading="lazy"/><div><span>Chennai · Tamil Nadu</span><b>Ingredients selected around real production needs.</b></div></div><div className={styles.whoCopy + " aboutReveal"}><span className={styles.eyebrow}>Who we are</span><h2 id="who-we-are-title">Local access. Professional ingredient support.</h2><p>We work with procurement teams, product developers, production teams, commercial bakeries, food processors and hospitality buyers who need a clearer path from ingredient enquiry to supply.</p><p>We help buyers define the application, grade, pack size, quantity, document requirements and supply expectations. Website information introduces sourcing options; final technical and regulatory approval remains with the buyer's qualified team.</p><div className={styles.industryPills}>{['Bakery','Chocolate','Beverages','Dairy & ice cream','Nutraceuticals','Food processing'].map(item=><span key={item}>{item}</span>)}</div></div></section>
    <section className={styles.qualitySection} aria-labelledby="quality-title"><div className={styles.qualityContent}><div className={styles.qualityHeading + " aboutReveal"}><span className={styles.eyebrow}>Quality and documentation</span><h2 id="quality-title">Product-specific information, not vague claims.</h2><p>Each enquiry should identify the product, grade, manufacturer or source, required documents and intended application. Where available, Vikranth coordinates specifications, COA, TDS, SDS and related supplier information for buyer review.</p><h3>Portfolio enquiry routes</h3><ul>{['CAMPCO','Roquette','Döhler','Nitta Gelatin India','Delta Nutritives','CP Kelco','Calpro Specialities','Anchor','Bakery ingredients','Other food ingredients'].map(item=><li key={item}>{item}</li>)}</ul></div><div className={styles.qualityImage + " aboutReveal"}><img src="/about-quality.webp" alt="Food ingredient samples reviewed for commercial sourcing" loading="lazy"/><span>Product documents vary by ingredient, grade and supplier</span></div></div><div className={styles.partnerMarquee + " aboutReveal"} aria-label="Ingredient manufacturer and supplier portfolios"><div className={styles.partnerMarqueeTrack}>{[...partners,...partners].map((partner,index)=><a href={`/associates/${partner.slug}`} key={`${partner.slug}-${index}`}><img src={partner.logo} alt={index < partners.length ? `${partner.name} logo` : ""}/><span>{partner.name}</span></a>)}</div></div></section>
    <section className={styles.finalCta}><span>Start a conversation</span><h2>Tell us what your product needs.</h2><p>Share your application, required ingredient, quantity and delivery location.</p><a href="/#contact">Request a Quote <ArrowRight/></a></section>  </>;
}
