"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowRight, BadgeCheck, Boxes, FileCheck2, Headphones, MapPin, PackageCheck, ShieldCheck, Sparkles, Truck } from "lucide-react";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import styles from "./about.module.css";
import { partners } from "../data/partners";

const frameCount = 300;
const frameUrl = index => `/about-sequence/frame-${String(index + 1).padStart(3, "0")}.webp`;
const chapters = [
  [0,74,"Chennai roots. India-wide ambition.","Ingredients that move production forward.","Vikranth Chemical Corporation connects food businesses with bakery, chocolate, dairy, beverage and specialty ingredients selected around real production needs."],
  [75,148,"Application-led sourcing","The right ingredient starts with the right questions.","We begin with your application, required function, grade, quantity and documentation needs—then help identify suitable options for evaluation."],
  [149,223,"A dependable ingredient network","Established partners. Practical local support.","Our supplier relationships and Chennai enquiry route help professional buyers navigate availability, specifications, samples and repeat requirements."],
  [224,299,"Built for business continuity","Responsive service beyond the first order.","From initial product matching to documentation and repeat supply conversations, our focus is clear communication and dependable support."],
];

function drawCover(canvas,image){const ctx=canvas.getContext("2d");const ratio=Math.min(window.devicePixelRatio||1,2.5);const width=canvas.clientWidth,height=canvas.clientHeight;if(canvas.width!==width*ratio||canvas.height!==height*ratio){canvas.width=width*ratio;canvas.height=height*ratio}ctx.setTransform(ratio,0,0,ratio,0,0);ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";ctx.fillStyle="#211007";ctx.fillRect(0,0,width,height);const scale=Math.min(width/image.naturalWidth,height/image.naturalHeight),rw=image.naturalWidth*scale,rh=image.naturalHeight*scale;ctx.drawImage(image,(width-rw)/2,(height-rh)/2,rw,rh)}

export default function AboutStory(){
  const sectionRef=useRef(null),canvasRef=useRef(null),imagesRef=useRef([]),currentFrame=useRef(0);
  const[loaded,setLoaded]=useState(0),[chapter,setChapter]=useState(0),[progress,setProgress]=useState(0);
  useEffect(()=>{gsap.registerPlugin(ScrollTrigger);let cancelled=false;const images=Array.from({length:frameCount},(_,index)=>{const image=new Image();image.decoding="async";image.src=frameUrl(index);image.onload=()=>{if(cancelled)return;setLoaded(value=>Math.min(frameCount,value+1));if(index===0&&canvasRef.current)drawCover(canvasRef.current,image)};return image});imagesRef.current=images;const playhead={frame:0};const render=()=>{const frame=Math.max(0,Math.min(frameCount-1,Math.round(playhead.frame)));currentFrame.current=frame;setProgress((frame/(frameCount-1))*100);const image=images[frame];if(image?.complete&&image.naturalWidth&&canvasRef.current)drawCover(canvasRef.current,image);const next=chapters.findIndex(item=>frame>=item[0]&&frame<=item[1]);if(next>=0)setChapter(previous=>previous===next?previous:next)};const tween=gsap.to(playhead,{frame:frameCount-1,ease:"none",onUpdate:render,scrollTrigger:{trigger:sectionRef.current,start:"top top",end:"bottom bottom",scrub:.35,invalidateOnRefresh:true}});const resize=()=>{const image=images[currentFrame.current];if(image?.complete&&image.naturalWidth&&canvasRef.current)drawCover(canvasRef.current,image)};window.addEventListener("resize",resize,{passive:true});return()=>{cancelled=true;window.removeEventListener("resize",resize);tween.scrollTrigger?.kill();tween.kill()}},[]);
  useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const items=gsap.utils.toArray(".aboutReveal");const reveals=items.map((item,index)=>gsap.fromTo(item,{autoAlpha:0,y:34},{autoAlpha:1,y:0,duration:.8,ease:"power3.out",scrollTrigger:{trigger:item,start:"top 86%",once:true},delay:(index%3)*.06}));return()=>{reveals.forEach(tween=>{tween.scrollTrigger?.kill();tween.kill()})}},[]);
  const active=chapters[chapter];
  return <>
    <section ref={sectionRef} className={styles.sequence} aria-label="The Vikranth story"><div className={styles.sticky}><canvas ref={canvasRef} className={styles.canvas}/><div className={styles.shade}/><div className={styles.progress} style={{"--progress":`${progress}%`}}/><div className={styles.storyCopy}><span>{active[2]}</span><h1>{active[3]}</h1><p>{active[4]}</p></div>{loaded<12&&<div className={styles.loader}><Sparkles/><span>Preparing the Vikranth story</span><small>{Math.round((loaded/12)*100)}%</small></div>}<div className={styles.scrollCue}>Scroll to explore <span/></div></div></section>
    <section className={styles.aboutOverview} aria-labelledby="about-overview-title">
      <div className={styles.aboutOverviewLead + " aboutReveal"}><span className={styles.eyebrow}>About Vikranth Chemical Corporation</span><h2 id="about-overview-title">A dependable ingredient partner for India’s food businesses.</h2><p>Vikranth Chemical Corporation is a Chennai-based supplier, wholesaler, distributor and importer of food ingredients. We help manufacturers and professional buyers find practical ingredient options for bakery, chocolate, biscuits, beverages, dairy, ice cream, jams, nutraceuticals and pharmaceutical applications.</p><a className={styles.textLink} href="/products">Explore our ingredient range <ArrowRight/></a></div>
      <div className={styles.aboutOverviewRail}>{[['01','Application-first sourcing','We start with the finished product, function, grade, quantity and documentation requirement.'],['02','A connected supplier network','Our portfolio brings together established manufacturers and specialist ingredient partners.'],['03','Support beyond the enquiry','From samples and specifications to repeat supply conversations, we keep the next step clear.']].map(([number,title,text])=><article className="aboutReveal" key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div>
    </section>
    <section className={styles.trustedCustomers} aria-labelledby="trusted-customers-title"><div className={styles.customerHeading + " aboutReveal"}><span id="trusted-customers-title" className={styles.eyebrow}>Trusted customers</span></div><div className={styles.customerMarquee} aria-label="Trusted customer logos"><div className={styles.customerMarqueeTrack}>{[['hershey.jpg','The Hershey Company'],['cavinkare.jpg','CavinKare'],['milka.jpg','Milka'],['lotte.jpg','Lotte'],['hershey.jpg','The Hershey Company'],['cavinkare.jpg','CavinKare'],['milka.jpg','Milka'],['lotte.jpg','Lotte']].map(([logo,name],index)=><div className={styles.customerLogo} key={`${name}-${index}`}><img src={`/trusted-customers/${logo}`} alt={`${name} logo`}/></div>)}</div></div></section>    <section className={styles.whoWeAre} aria-labelledby="who-we-are-title"><div className={styles.whoMedia + " aboutReveal"}><video autoPlay muted loop playsInline preload="metadata" poster="/partner-products/campco-cocoa.webp"><source src="/about-food-b2b.mp4" type="video/mp4"/></video><div><span>Chennai · Tamil Nadu</span><b>Ingredients selected around real production needs.</b></div></div><div className={styles.whoCopy + " aboutReveal"}><span className={styles.eyebrow}>Who we are</span><h2 id="who-we-are-title">Local access. Professional ingredient support.</h2><p>Our network has a strong presence across South India and supports food businesses across India. The products we represent are used by bakeries, chocolate makers, biscuit manufacturers, beverage and ice-cream businesses, jam producers, pharmaceutical companies and food supplement manufacturers.</p><p>We make sourcing easier to navigate by helping buyers move from a broad requirement to a clearer product conversation: application, grade, pack size, quantity, documents, sample availability and supply expectations.</p><div className={styles.industryPills}>{['Bakery','Chocolate','Beverages','Dairy & ice cream','Pharma','Food supplements'].map(item=><span key={item}>{item}</span>)}</div></div></section>
    <section className={styles.qualitySection} aria-labelledby="quality-title"><div className={styles.qualityContent}><div className={styles.qualityHeading + " aboutReveal"}><span className={styles.eyebrow}>Quality assurance</span><h2 id="quality-title">Care from sourcing to final supply.</h2><p>From collecting centres in cocoa-growing areas to final processing and packing, quality is considered at every stage. We work with supplier specifications and documentation to help buyers evaluate ingredients with confidence.</p><h3>Our product network</h3><ul>{['Campco Ltd','Roquette Riddhi Siddhi Products','Döhler India Private Ltd','Nitta Gelatin India Ltd','Delta Nutritives Pvt Ltd','CP Kelco India','Calpro Foods Private Ltd','Anchor Products','Beverages & Jams','Other Products'].map(item=><li key={item}>{item}</li>)}</ul></div><div className={styles.qualityImage + " aboutReveal"}><img src="/partner-products/campco-cocoa.webp" alt="Campco cocoa and chocolate ingredients"/><span>Ingredient partners for food manufacturing</span></div></div><div className={styles.partnerMarquee + " aboutReveal"} aria-label="Vikranth ingredient partners"><div className={styles.partnerMarqueeTrack}>{[...partners,...partners].map((partner,index)=><a href={`/associates/${partner.slug}`} key={`${partner.slug}-${index}`}><img src={partner.logo} alt={`${partner.name} logo`}/><span>{partner.name}</span></a>)}</div></div></section>    <section className={styles.faqSection} aria-labelledby="faq-title"><div className="aboutReveal"><span className={styles.eyebrow}>Frequently asked questions</span><h2 id="faq-title">Useful answers before you enquire.</h2></div><div className={styles.faqGrid}>{[['What does Vikranth Chemical Corporation supply?','We supply and distribute food ingredients and specialty ingredients for bakery, chocolate, dairy, beverages, ice cream, jams, nutraceutical and pharmaceutical applications.'],['Where does Vikranth supply?','We are based in Chennai and support professional buyers across India, with a strong network across South India.'],['Can I request samples or product documents?','Yes. Share the application, product requirement, quantity and delivery location so our team can advise on available samples, specifications and next steps.'],['How do I contact Vikranth for a quotation?','Use the Request a Quote link or contact our Chennai team with your ingredient requirement and commercial details.']].map(([question,answer])=><details className="aboutReveal" key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className={styles.finalCta}><span>Start a conversation</span><h2>Tell us what your product needs.</h2><p>Share your application, required ingredient, quantity and delivery location.</p><a href="/#contact">Request a Quote <ArrowRight/></a></section>  </>;
}
