import LegalPage from "../components/LegalPage";

export const metadata = {
  title: "Privacy Policy | Vikranth Chemical Corporation",
  description: "Read how Vikranth Chemical Corporation handles website enquiries, contact information, analytics and business communications.",
  alternates: { canonical: "/privacy/" },
};

const sections = [
  { heading: "Legal-review notice and scope", content: ["This policy describes the website's current intended data practices and must be reviewed against Vikranth Chemical Corporation's actual systems, vendors, retention periods and applicable Indian law by a qualified legal or privacy professional.", "It applies to information received through website forms and related business-enquiry channels from 19 August 2026."] },
  { heading: "Information we receive", content: ["When you request a quotation, product document, sample or callback, we may receive your name, company, business contact details, ingredient requirement, quantity, delivery location and message.", "We may also receive basic technical information supplied by your browser, hosting provider or analytics service, such as device type, browser type, pages visited and approximate location."] },
  { heading: "How we use information", content: ["We use enquiry information to respond, evaluate availability, coordinate with relevant suppliers or service providers where necessary, maintain business records and communicate about the requested service.", "Marketing communication, if introduced, should use separate optional consent and a clear opt-out process."] },
  { heading: "WhatsApp and external services", content: ["Some forms continue through WhatsApp or open external services such as Google Maps, email or social media. Information shared through those services is also governed by their own privacy terms.", "The website does not ask for payment card details or account passwords through its enquiry forms."] },
  { heading: "Sharing, processors and transfers", content: ["We do not sell personal information. Information may be shared with relevant team members, hosting or communication providers, or ingredient partners only when reasonably necessary to respond to the requirement.", "Any processors, international transfers or additional recipients must be documented here after the company's actual vendors and data flows are confirmed."] },
  { heading: "Retention and security", content: ["Enquiry records are retained only as long as needed for communication, legal obligations, supply coordination and legitimate record keeping. Exact retention periods must be approved and published after operational review.", "Reasonable administrative and technical safeguards are used, but no internet transmission or storage method can be guaranteed completely secure."] },
  { heading: "Security and your choices", content: ["We use reasonable administrative and technical safeguards, but no internet transmission or storage method can be guaranteed to be completely secure.", "You may ask us to correct or delete information you previously supplied, subject to legal and legitimate business-record requirements."] },
  { heading: "Visitor rights and requests", content: ["You may ask to access, correct or delete information you supplied, subject to legal and legitimate business-record requirements. Contact vikranth.chemicals@gmail.com or +91 87544 42924.", "The website is intended for business users and is not directed to children. Cookie or analytics choices will be described when the actual tools and consent requirements are confirmed."] },
  { heading: "Policy updates and contact", content: ["We may update this policy when the website, services or legal requirements change. The latest revision date appears at the top of this page.", "Privacy and grievance contact arrangements must be confirmed through legal review before production publication."] },
];

export default function PrivacyPage() {
  const schema = [{ "@context": "https://schema.org", "@type": "WebPage", url: "https://www.vikranthchem.com/privacy/", name: "Privacy Policy", description: metadata.description }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://www.vikranthchem.com/" }, { "@type": "ListItem", position: 2, name: "Privacy Policy", item: "https://www.vikranthchem.com/privacy/" }] }];
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><LegalPage eyebrow="Your information" title="Privacy Policy" introduction="Vikranth Chemical Corporation respects the privacy of website visitors and business contacts. This policy explains the information received through the website and enquiry channels, why it is used and how to contact us. Legal review against actual data practices is required." updated="19 August 2026" sections={sections} /></>;
}
