import Link from "next/link";
import { ArrowRight, Check, FileText, PackageCheck, Truck } from "lucide-react";
import { industries } from "./data/catalog";
import { hubContent } from "./data/industry-content";
import { DetailHeader, DetailFooter, PageCta, styles } from "./components/DetailChrome";
const siteUrl = "https://www.vikranthchemicalcorporation.com";
export const metadata = { title: hubContent.title, description: hubContent.description, keywords: ["food ingredients supplier in Chennai", "food ingredients supplier in India", "B2B food ingredient distributor Chennai", "bulk food ingredients"], alternates: { canonical: "/industries/" }, robots: { index: true, follow: true }, openGraph: { type: "website", url: "/industries/", title: hubContent.title, description: hubContent.description, siteName: "Vikranth Chemical Corporation", locale: "en_IN", images: [{ url: industries[0].image, alt: "Food ingredient solutions by industry" }] } };
export default function IndustriesPage() {
  const schema = [{ "@context": "https://schema.org", "@type": "CollectionPage", url: `${siteUrl}/industries/`, name: hubContent.h1, description: hubContent.summary, about: { "@id": `${siteUrl}/#organization` }, mainEntity: { "@type": "ItemList", itemListElement: industries.map((item, i) => ({ "@type": "ListItem", position: i + 1, name: item.name, url: `${siteUrl}/industries/${item.slug}/` })) } }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${siteUrl}/` }, { "@type": "ListItem", position: 2, name: "Industries", item: `${siteUrl}/industries/` }] }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: hubContent.faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) }];
  return <main className={`${styles.page} ${styles.industryPage}`}><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><DetailHeader />
    <section className={`${styles.industryHero} ${styles.hubHero}`}><div className={styles.hubMosaic}>{industries.slice(0, 4).map((item) => <img key={item.slug} src={item.image} alt="" />)}</div><div className={styles.industryHeroShade} /><div className={styles.industryHeroInner}><div className={styles.industryHeroGrid}><div><span className={styles.heroKicker}>One sourcing partner · Multiple food applications</span><h1>{hubContent.h1}</h1><p>{hubContent.summary}</p><div className={styles.heroActions}><Link href="#industry-directory">Browse industries <ArrowRight size={16} /></Link><Link href="/contact#enquiry">Talk to our team</Link></div></div><aside className={styles.heroProof}><span>B2B procurement support</span><ul><li><PackageCheck /><b>11 application sectors</b><small>Organised by what you manufacture</small></li><li><FileText /><b>Grade & document checks</b><small>Specification-led enquiries</small></li><li><Truck /><b>India supply support</b><small>Subject to product and location</small></li></ul></aside></div></div></section>
    <div className={styles.industryContent}><section className={styles.decisionIntro}><div><span className={styles.sectionNumber}>01</span><small className={styles.eyebrow}>Ingredient sourcing, made clearer</small><h2>Choose by manufacturing application</h2></div><div><p>{hubContent.introduction}</p><div className={styles.trustLine}><Check /> Commercial sourcing <Check /> Product matching <Check /> Pan-India enquiries</div></div></section>
      <section className={styles.directorySection} id="industry-directory"><div className={styles.sectionHeading}><div><span className={styles.sectionNumber}>02</span><small className={styles.eyebrow}>Industry directory</small><h2>Find ingredients for your production line</h2></div><p>Each sector page combines relevant product families, practical selection guidance and a quote-ready procurement checklist.</p></div><div className={styles.industryDirectory}>{industries.map((item, i) => <Link href={`/industries/${item.slug}`} key={item.slug}><div className={styles.directoryImage}><img src={item.image} alt={`${item.name} solutions`} /><span>{String(i + 1).padStart(2, "0")}</span></div><div><small>B2B solutions</small><h3>{item.name}</h3><p>{item.summary}</p><b>Explore industry <ArrowRight size={15} /></b></div></Link>)}</div></section>
      <section className={styles.applicationSection}><div className={styles.sectionHeading}><div><span className={styles.sectionNumber}>03</span><small className={styles.eyebrow}>Portfolio at a glance</small><h2>Four routes into the right ingredient family</h2></div></div><div className={styles.applicationGrid}>{hubContent.applications.map(([name, description], i) => <article key={name}><span>0{i + 1}</span><h3>{name}</h3><p>{description}</p></article>)}</div></section>
      <section className={styles.faqSection}><div className={styles.faqIntro}><span className={styles.sectionNumber}>04</span><small className={styles.eyebrow}>Procurement essentials</small><h2>Frequently asked questions</h2><p>What buyers need to know before requesting a product, grade, document or sample.</p></div><div className={styles.faqList}>{hubContent.faq.map(([q, a], i) => <details key={q} open={i === 0}><summary><span>0{i + 1}</span>{q}<b>+</b></summary><p>{a}</p></details>)}</div></section>
    </div><PageCta title="Tell us what you manufacture" product="Food ingredient requirement" /><DetailFooter /></main>;
}
