import LegalPage from "../components/LegalPage";

export const metadata = {
  title: "Terms of Use | Vikranth Chemical Corporation",
  description: "Read the terms governing Vikranth's website, product information, enquiries, documents, trademarks and external links.",
  alternates: { canonical: "/terms/" },
};

const sections = [
  { heading: "Legal-review notice and acceptance", content: ["These website terms are not a substitute for quotation, invoice or supply-contract terms. They require legal review and alignment with Vikranth Chemical Corporation's actual commercial practice.", "By using the website, you agree to use it lawfully and not interfere with its operation, security, content or availability. These terms apply from 19 August 2026."] },
  { heading: "Product information and technical responsibility", content: ["Product descriptions are provided for general sourcing and enquiry purposes. Availability, manufacturer, grade, specification, pack size, MOQ, price, lead time and supporting documents may change and must be confirmed in writing for each transaction.", "Buyers are responsible for evaluating suitability, compliance, formulation, dosage, labelling, storage and use with qualified technical and regulatory personnel."] },
  { heading: "Quotations and orders", content: ["Submitting an enquiry does not create a purchase contract. A transaction is formed only after commercial terms, product details, quantity, delivery and acceptance are confirmed through the applicable business process.", "Customers are responsible for confirming that selected ingredients and their intended use satisfy relevant formulation, safety, labelling and regulatory requirements."] },
  { heading: "Intellectual property, trademarks and brochures", content: ["Website text, layout, graphics, branding and original materials belong to Vikranth Chemical Corporation or their respective owners and may not be copied or commercially reused without permission.", "Third-party brand names, product names and logos are the property of their respective owners. Their appearance does not imply an exclusive or authorised relationship unless expressly stated and supported by current documentation. Brochures and documents may be used only for legitimate evaluation and enquiry." ] },
  { heading: "External links and availability", content: ["Links to WhatsApp, maps, social platforms, manufacturer resources and other external services are provided for convenience. We do not control their availability, security or content.", "We aim to keep website information accurate and available but do not guarantee uninterrupted access or that every page will always be error-free or current."] },
  { heading: "Liability, indemnity and governing law", content: ["To the extent permitted by law, Vikranth Chemical Corporation is not responsible for indirect losses arising solely from reliance on general website information or external services. Any indemnity and limitation wording requires legal approval.", "These terms are intended to be governed by the laws of India, with jurisdiction to be confirmed through legal review. Questions may be sent to vikranth.chemicals@gmail.com or +91 87544 42924 in Chennai, Tamil Nadu."] },
  { heading: "Updates and contact", content: ["Website access, content and these terms may be updated when maintenance, security, legal or business requirements change.", "Contact Vikranth through the website contact page for questions about these terms or website information."] },
];

export default function TermsPage() {
  const schema = [{ "@context": "https://schema.org", "@type": "WebPage", url: "https://www.vikranthchemicalcorporation.com/terms/", name: "Website Terms of Use", description: metadata.description }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://www.vikranthchemicalcorporation.com/" }, { "@type": "ListItem", position: 2, name: "Terms of Use", item: "https://www.vikranthchemicalcorporation.com/terms/" }] }];
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><LegalPage eyebrow="Website terms" title="Website Terms of Use" introduction="These terms govern use of Vikranth's website, product information, enquiries, documents, trademarks and external links. They are separate from quotation, invoice and supply-contract terms and require legal review." updated="19 August 2026" sections={sections} /></>;
}
