import Link from "next/link";
import { notFound } from "next/navigation";
import { partners,getPartner } from "../../data/partners";
import { getProduct,getIndustry,slugify } from "../../data/catalog";
import { DetailHeader,DetailFooter,PageCta,styles } from "../../components/DetailChrome";
export function generateStaticParams(){return partners.map(({slug})=>({slug}));}
export async function generateMetadata({params}){const partner=getPartner((await params).slug);if(!partner)return{};return{title:`${partner.name} Products in Chennai | Vikranth Chemical Corporation`,description:`Explore ${partner.name} ${partner.summary} through Vikranth Chemical Corporation in Chennai. Confirm current products, documents, samples and quotation availability.`};}
export default async function PartnerPage({params}){
 const partner=getPartner((await params).slug);if(!partner)notFound();
 const productLinks=partner.products.map(name=>getProduct(slugify(name))).filter(Boolean);
 const industryLinks=partner.industries.map(getIndustry).filter(Boolean);
 const faq=[`What ${partner.name} products can I enquire about in Chennai?`,`Can Vikranth help with ${partner.name} product documents or samples?`,`Can I request ${partner.name} products in bulk?`,`What information is needed for a ${partner.name} quotation?`];
 return <main className={styles.page}><DetailHeader/>
  <section className={`${styles.hero} ${styles.partnerHero}`}><img className={styles.heroImage} src={partner.image} alt={`${partner.name} ingredient applications`}/><div className={styles.heroCopy}><div className={styles.crumbs}><Link href="/">Home</Link><span>/</span><Link href="/associates">Associates</Link><span>/</span><span>{partner.name}</span></div><small>Partner ingredient solutions</small><h1>{partner.name}<br/>Ingredient Solutions<br/>in Chennai</h1><p>Vikranth Chemical Corporation provides a Chennai enquiry route for businesses evaluating {partner.summary}. Share your application, grade, quantity and document requirements.</p><div className={styles.heroActions}><Link href={`/?partner=${encodeURIComponent(partner.name)}#contact`}>View Relevant Products →</Link><Link href="/#contact">Request a Quote</Link></div>{partner.logo&&<div className={styles.partnerLogo}><img src={partner.logo} alt={`${partner.name} logo`}/></div>}</div></section>
  <div className={styles.content}>
   <section className={styles.facts}><div><small>Support</small><b>Chennai enquiry route</b></div><div><small>Selection</small><b>Application-led</b></div><div><small>Supply</small><b>Subject to confirmation</b></div><div><small>Documents</small><b>On request</b></div></section>
   <section className={styles.answer}><div className={styles.answerIcon}>◎</div><div><h2>About {partner.name}</h2><p>{partner.about}</p></div></section>
   <h2 className={styles.sectionTitle}>{partner.name} product categories</h2><section className={styles.productGrid}>{productLinks.map(product=><Link className={styles.productCard} href={`/products/${product.slug}`} key={product.slug}><img src={product.image} alt=""/><div><h3>{product.name}</h3><p>View product details →</p></div></Link>)}</section>
   <h2 className={styles.sectionTitle}>Applications supported through the {partner.name} enquiry route</h2><section className={styles.benefits}>{industryLinks.slice(0,5).map((industry,i)=><Link className={styles.linkTile} href={`/industries/${industry.slug}`} key={industry.slug}><span>0{i+1}</span><strong>{industry.name}</strong></Link>)}</section>
   <section className={styles.split}><img src={partner.image} alt={`${partner.name} ingredient supply`} style={{width:"100%",height:"100%",minHeight:300,objectFit:"cover",borderRadius:12}}/><div className={styles.panel}><small className={styles.eyebrow}>A local sourcing route for Chennai buyers</small><h2>Product matching and enquiry support</h2><p>Ask the Vikranth team to confirm the current catalogue, product fit, grade, pack size, documents, sample availability, order quantity, lead time and delivery coverage for your application.</p><Link className={styles.primary} href="/#contact">Request Products / Documents →</Link></div></section>
   <h2 className={styles.sectionTitle}>What to confirm before ordering</h2><section className={styles.checklist}>{["Finished product and application","Required product or grade","Quantity and delivery location","Specification and COA documents","Trial quantity and timeline"].map((item,i)=><article key={item}><span>0{i+1}</span><strong>{item}</strong></article>)}</section>
   <section className={styles.split}><div className={styles.panel}><h3>Documents and sample support</h3><ul><li>Product specification sheet</li><li>COA and regulatory documents</li><li>Current pack-size information</li><li>Sample availability</li></ul></div><div className={styles.panel}><h3>Related industries</h3>{industryLinks.map(industry=><Link className={styles.inlineLink} href={`/industries/${industry.slug}`} key={industry.slug}>{industry.name} →</Link>)}</div></section>
   <section className={styles.faq}><h2 className={styles.sectionTitle}>Frequently asked questions</h2>{faq.map(question=><details key={question}><summary>{question}</summary><p>Share the exact product, application, grade, quantity, delivery location and documents required. Vikranth will confirm current availability, sample status and supply coverage before providing a definitive answer.</p></details>)}</section>
  </div><PageCta title={`Need help with a ${partner.name} ingredient?`} product={partner.name}/><DetailFooter/>
 </main>
}
